backend:
  name: github
  repo: tonny008/linkagritech-site 
  branch: main
media_folder: static/images
public_folder: images
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'data/homepage.yml'
        fields:
          - { name: 'banner', label: Banner, widget: 'object', fields: [
            {label: "enable", name: "enable", widget: boolean},
            {label: "title", name: "title", widget: string},
            {label: "content", name: "content", widget: string},
            {label: "image", name: "image", widget: image},
            {label: "button", name: "button", widget: object, fields: [
              {label: "enable", name: "enable", widget: boolean},
              {label: "label", name: "label", widget: string},
              {label: "link", name: "link", widget: string}
            ]}
          ]}
          - { name: 'mission', label: mission, widget: 'object', fields: [
            {label: "enable", name: "enable", widget: boolean},
            {label: "title", name: "title", widget: string},
            {label: "content", name: "content", widget: string},
            {label: "video_thumb", name: "video_thumb", widget: image},
            {label: "video_id", name: "video_id", widget: string}
          ]}
          - { name: 'vision', label: vision, widget: 'object', fields: [
            {label: "enable", name: "enable", widget: boolean},
            {label: "section", name: "section", widget: string},
            {label: "vision_item", name: "vision_item", widget: 'list', fields: [
              {label: "title", name: "title", widget: string},
              {label: "image", name: "image", widget: image},
              {label: "content", name: "content", widget: string}
            ]}
          ]}
          - { name: 'product', label: product, widget: 'object', fields: [
            {label: "enable", name: "enable", widget: boolean},
            {label: "section", name: "section", widget: string},
            {label: "title", name: "title", widget: string},
            {label: "content", name: "content", widget: string},
            {label: "product_item", name: "product_item", widget: list, fields: [
              {label: "title", name: "title", widget: string},
              {label: "image", name: "image", widget: image},
              {label: "content", name: "content", widget: string},
              {label: "project_url", name: "project_url", widget: string}
            ]}
          ]}
          - { name: 'contact', label: contact, widget: 'object', fields: [
            {label: "enable", name: "enable", widget: boolean},
            {label: "section", name: "section", widget: string},
            {label: "title", name: "title", widget: string},
            {label: "image", name: "image", widget: image},
            {label: "content", name: "content", widget: string},
          ]}
          - { name: 'call_to_action', label: call_to_action, widget: 'object', fields: [
            {label: "enable", name: "enable", widget: boolean},
            {label: "title", name: "title", widget: string},
            {label: "button_label", name: "button_label", widget: string},
            {label: "button_link", name: "button_link", widget: string},
          ]}
